### ISSUE TITLE
Discovered problems in unitPrice.js

### ISSUE THREAD

**Issue by Lognam-Huang** [yzhu27/UnitPriceHelper#6]
Problem 1:
For if the **quantity** of the item is not in digits, for example, **"1/2" or "0.5"**, the js file cannot get the correct result yet.
This may be solved by **_updating regular expression later_**?

Problem 2:
There may be cases that the **price/unit is already been provided**, but this is not considered/distuiguish by the js file yet.
Notice that **the format is "$[digits]/[unit]"**.
This can be solved by **_adding an if statement before applying regular expression_**.

Problem 3:
The **style** of inserted tag (span) does not apply **CSS changes**.
The reason is not yet found.

Somebody is yelling outside right now :)

**Comment by Lognam-Huang** [comment]
Problem 1 update: 
**Decimal number** such as 0.5 **can be handled** by updating Regular Expression.
Thanks to yZhu.

**Comment by Lognam-Huang** [comment]
Problem 2 update:
**Provided price/unit is solved** by re-constructing logic.

**Comment by yzhu27** [comment]
Problems solved

**Comment by yzhu27** [comment]
bug fixed
