### ISSUE TITLE
Bug in Target.js

### ISSUE THREAD

**Issue by MZWANGgg** [yzhu27/UnitPriceHelper#9]
In the code for Items Page, _Insert_ function will fail with parameter >= 7 if you run the code together.
But if you run them separately, the function can work. Weird.

**Comment by yzhu27** [comment]
Is it still buggy after @Internationale-NCSU's reconstruction of the code? If not, this issue may need to be closed.

**Comment by MZWANGgg** [comment]
Thanks to Internationale-NCSU's reconstruction of the code, it has been solved.
